name = "CompiledWebservice"
uuid = "9c443105-9363-4724-ab64-6abe9d30bf12"
authors = ["Jędrzej Lewandowski <jedrzejblew@gmail.com>"]
version = "0.1.0"

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
